---
title: "C6320 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6320"
helpviewer_keywords: 
  - "C6320"
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 10
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 10
---
# C6320
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

avviso C6320: l'espressione di filtro eccezioni è la costante EXCEPTION\_EXECUTE\_HANDLER.  Questa condizione potrebbe mascherare eccezioni la cui gestione non è prevista  
  
 L'avviso indica l'effetto collaterale dell'utilizzo della costante EXCEPTION\_EXECUTE\_HANDLER in un blocco \_\_except.  In questo caso l'istruzione nel blocco \_\_except verrà sempre eseguita per gestire le eccezioni, incluse quelle che non si desidera gestire in una determinata funzione.  Si consiglia di verificare l'eccezione prima di gestirla.  
  
## Esempio  
 Il codice seguente genera questo avviso perché il blocco \_\_except tenta di gestire tutti i tipi di eccezioni:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Per risolvere il problema, utilizzare `GetExceptionCode` per verificare una determinata eccezione prima di gestirla, come illustrato nel codice riportato di seguito:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## Vedere anche  
 [Istruzione try\-except](/visual-cpp/cpp/try-except-statement)